Adding Database
Albertamoahjunior/RGT-learning pull request #6
Opened 2024-10-30 17:39 UTC by Albertamoahjunior

I have connected the backend to a database now.  
Instead of using json file as the database, now postgre is been used as database.

2024-11-04 08:49 UTC, genes2160 commented on backend/dbconfig.ts
This needs to be removed into env

2024-11-04 08:49 UTC, genes2160 commented on backend/server.ts
Why did you remove CORS ?

2024-11-04 08:50 UTC, genes2160 commented on backend/src/controllers.ts
Looks good

2024-11-04 08:51 UTC, Albertamoahjunior commented on backend/dbconfig.ts
Yes please.

2024-11-04 08:52 UTC, genes2160 requested changes
<img width="583" alt="image" src="https://github.com/user-attachments/assets/14f1f849-9440-4aeb-81ff-f54111d33967">

This indicates that adding a new task does not work i.e. The entries never make it into the db

Always ensure that the entries make way into the DB and debug errors you find
<img width="892" alt="image" src="https://github.com/user-attachments/assets/869a861b-812d-4218-81ac-09872f4fb25c">

2024-11-04 08:53 UTC, Albertamoahjunior commented on backend/server.ts
I actually removed for testing purpose, to make sure the integration was working before I implement it again but I think I forgot to implement it again after I was done.

2024-11-04 08:54 UTC, Albertamoahjunior commented on backend/src/controllers.ts
Yes please

2024-11-04 08:54 UTC, genes2160 commented
<img width="889" alt="image" src="https://github.com/user-attachments/assets/1d9c2044-b57d-4763-ba18-e639a511cf76">
Is this how the UI is intended ????

2024-11-05 10:07 UTC, genes2160 commented on frontend/src/components/taskcontainer.tsx
Next time delegate the 
```
http://localhost:2000
```
to its own file i.e. .env and import across so when the host changes there wont be a problem 

When it comes to this never hard code simply delegate to .env

2024-11-05 10:08 UTC, Albertamoahjunior commented on frontend/src/components/taskcontainer.tsx
Yes please

2024-11-05 10:09 UTC, genes2160 approved these changes
Just few comments 
1. next time delegate a single .env that front and backend can make use of
i.e. structure can be 
|___.env (this ignored by git)
|____.env.example(this pushed to git)
|
|___frontend(folder)
|
|___backend(folder)


The both front and back can consume the .env

2024-11-05 10:10 UTC, merged